#!/usr/bin/env bash

BIN_DIR=${BIN_DIR:-/usr/local/bin}
INSTALL=install

echo "Installing conftpl to $BIN_DIR/conftpl"
$INSTALL -c bin/conftpl $BIN_DIR/conftpl
echo "Installing confadm to $BIN_DIR/confadm"
$INSTALL -c bin/confadm $BIN_DIR/confadm
$INSTALL confmgr.toml /etc/confmgr.toml
